[package]
name = "rpds"
description = "Persistent data structures with structural sharing"
version = "0.5.0"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

homepage = "https://github.com/orium/rpds"
repository = "https://github.com/orium/rpds"
documentation = "https://docs.rs/rpds"
readme = "README.md"

keywords = [
    "data-structure",
    "data-structures",
    "persistent",
    "immutable",
]
categories = [
    "data-structures",
]

license = "MPL-2.0"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
]

[badges]
travis-ci = { repository = "orium/rpds", branch = "master" }
codecov = { repository = "orium/rpds", branch = "master", service = "github" }

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
# TODO This will probably be part of rust in the future (see https://github.com/rust-lang/rust/issues/29553)
criterion = "0.2"
rand = "0.5"
# needed to test serde
bincode = "1"
pretty_assertions = "0.5"

[features]
fatal-warnings = []

[package.metadata.docs.rs]
features = ["serde"]
